// Amber (#E3C77E) is the ball and the decision lamp. It is not a general fill.

export const colors = {
  bg: '#0F1A16',
  bg2: '#16231E',
  text: '#EDE6D6',
  body: '#D3CCBB',
  muted: '#93A097',
  line: 'rgba(237, 230, 214, 0.16)',
  invert: '#EDE6D6',
  invertText: '#0F1A16',
  inkOnBone: '#2B3530',
  brass: '#C9A24D',
  brassInk: '#7E5E14',
  forest: '#0F1A16',
  forestLift: '#1C2C25',
  surface: '#16231E',
  bone: '#EDE6D6',
  deepBrass: '#7E5E14',
  amber: '#E3C77E',
  reelWell: '#111D18',
  paid: '#9CC9A8',
  refused: '#E4A48E',
  tilt: '#F2B94B',
  lampOff: 'rgba(201, 162, 77, 0.18)',
  blockOff: 'rgba(201, 162, 77, 0.18)',
  track: 'rgba(237, 230, 214, 0.14)',
  brassLine: 'rgba(201, 162, 77, 0.55)',
  brassSoft: 'rgba(201, 162, 77, 0.45)',
  ink: '#1A1608',
  inkSoft: '#3A2E0E',
  plaqueDate: '#4A3A10',
  holdHint: '#3A2E0E',
  edgeHighlight: '#E9D28C',
  edgeMid: '#A5822F',
  paidWash: 'rgba(156, 201, 168, 0.12)',
  refusedWash: 'rgba(228, 164, 142, 0.12)',
  boneLine: 'rgba(237, 230, 214, 0.10)',
  brassWash: 'rgba(201, 162, 77, 0.14)',
} as const;

export const fonts = {
  serif: 'Fraunces_500Medium',
  serifLight: 'Fraunces_300Light',
  serifRegular: 'Fraunces_400Regular',
  serifItalic: 'Fraunces_400Regular_Italic',
  sans: 'Manrope_400Regular',
  sansMedium: 'Manrope_500Medium',
  sansSemibold: 'Manrope_600SemiBold',
  sansBold: 'Manrope_700Bold',
  mono: 'monospace',
} as const;

export const space = {
  xs: 4,
  sm: 6,
  md: 8,
  lg: 10,
  xl: 12,
  xxl: 14,
  xxxl: 16,
  screen: 24,
  screenWide: 28,
  bottom: 26,
} as const;

export const radii = {
  bar: 2,
  reel: 10,
  stat: 12,
  control: 12,
  plaque: 14,
  card: 16,
  cta: 16,
  row: 18,
  hold: 18,
  frameInner: 20,
  frame: 22,
  pill: 999,
} as const;

export const touchTarget = 44;

export const type = {
  display: {
    fontFamily: fonts.serifRegular,
    fontSize: 34,
    lineHeight: 37,
    letterSpacing: -0.34,
    color: colors.bone,
  },
  displayLarge: {
    fontFamily: fonts.serifRegular,
    fontSize: 40,
    lineHeight: 43,
    letterSpacing: -0.4,
    color: colors.bone,
  },
  title: {
    fontFamily: fonts.serif,
    fontSize: 22,
    lineHeight: 24,
    color: colors.bone,
  },
  wordmark: {
    fontFamily: fonts.serif,
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: 0.4,
    color: colors.bone,
  },
  reel: {
    fontFamily: fonts.serif,
    fontSize: 28,
    lineHeight: 32,
    color: colors.brass,
  },
  figure: {
    fontFamily: fonts.serifLight,
    fontSize: 64,
    lineHeight: 64,
    letterSpacing: -1.28,
    color: colors.bone,
  },
  stat: {
    fontFamily: fonts.serifRegular,
    fontSize: 24,
    lineHeight: 24,
    color: colors.bone,
  },
  plaqueTitle: {
    fontFamily: fonts.serif,
    fontSize: 19,
    lineHeight: 22,
    color: colors.ink,
  },
  body: {
    fontFamily: fonts.sans,
    fontSize: 15,
    lineHeight: 22,
    color: colors.body,
  },
  ui: {
    fontFamily: fonts.sansSemibold,
    fontSize: 14,
    lineHeight: 18,
    color: colors.body,
  },
  button: {
    fontFamily: fonts.sansBold,
    fontSize: 17,
    lineHeight: 22,
    color: colors.forest,
  },
  caption: {
    fontFamily: fonts.sans,
    fontSize: 12,
    lineHeight: 16,
    color: colors.muted,
  },
  kicker: {
    fontFamily: fonts.sansBold,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.92,
    color: colors.brass,
  },
  micro: {
    fontFamily: fonts.sansBold,
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1.54,
    color: colors.muted,
  },
  stage: {
    fontFamily: fonts.sansBold,
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.6,
    color: colors.bone,
  },
  tab: {
    fontFamily: fonts.sansBold,
    fontSize: 12,
    lineHeight: 16,
  },
  pill: {
    fontFamily: fonts.sansSemibold,
    fontSize: 13,
    lineHeight: 16,
  },
} as const;
